config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :mobiles
  	root "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mobile.rb
class Mobile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
 # protect_from_forgery with: :exception
 protect_from_forgery prepend: true
end

app/controllers/mobiles_controller.rb
class MobilesController < ApplicationController
  before_action :set_mobile, only: [:show, :edit, :update, :destroy]

  # GET /mobiles
  # GET /mobiles.json
  def index
    @mobiles = Mobile.all
  end

  # GET /mobiles/1
  # GET /mobiles/1.json
  def show
  end

  # GET /mobiles/new
  def new
    @mobile = Mobile.new
  end

  # GET /mobiles/1/edit
  def edit
  end

  # POST /mobiles
  # POST /mobiles.json
  def create
    @mobile = Mobile.new(mobile_params)

    respond_to do |format|
      if @mobile.save
        format.html { redirect_to @mobile, notice: 'Mobile was successfully created.' }
        format.json { render :show, status: :created, location: @mobile }
      else
        format.html { render :new }
        format.json { render json: @mobile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mobiles/1
  # PATCH/PUT /mobiles/1.json
  def update
    respond_to do |format|
      if @mobile.update(mobile_params)
        format.html { redirect_to @mobile, notice: 'Mobile was successfully updated.' }
        format.json { render :show, status: :ok, location: @mobile }
      else
        format.html { render :edit }
        format.json { render json: @mobile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mobiles/1
  # DELETE /mobiles/1.json
  def destroy
    @mobile.destroy
    respond_to do |format|
      format.html { redirect_to mobiles_url, notice: 'Mobile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mobile
      @mobile = Mobile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mobile_params
      params.require(:mobile).permit(:name, :brand, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mobiles_helper.rb
module MobilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Showroom</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/mobiles/_form.html.erb
<%= form_with(model: mobile, local: true) do |form| %>
  <% if mobile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mobile.errors.count, "error") %> prohibited this mobile from being saved:</h2>

      <ul>
      <% mobile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :mobile_name %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :mobile_brand %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :mobile_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mobiles/edit.html.erb
<h1>Editing Mobile</h1>

<%= render 'form', mobile: @mobile %>

<%= link_to 'Show', @mobile %> |
<%= link_to 'Back', mobiles_path %>

app/views/mobiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mobiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mobiles.each do |mobile| %>
      <tr>
        <td><%= mobile.name %></td>
        <td><%= mobile.brand %></td>
        <td><%= mobile.price %></td>
        <td><%= link_to 'Show', mobile %></td>
        <td><%= link_to 'Edit', edit_mobile_path(mobile) %></td>
        <td><%= link_to 'Destroy', mobile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mobile', new_mobile_path %>

app/views/mobiles/new.html.erb
<h1>New Mobile</h1>

<%= render 'form', mobile: @mobile %>

<%= link_to 'Back', mobiles_path %>

app/views/mobiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mobile.name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @mobile.brand %>
</p>

<p>
  <strong>Price:</strong>
  <%= @mobile.price %>
</p>

<%= link_to 'Edit', edit_mobile_path(@mobile) %> |
<%= link_to 'Back', mobiles_path %>